# Generated by Django 5.2 on 2025-09-04 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Elemen',
                'verbose_name_plural': 'Elemen',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kriteria',
                'verbose_name_plural': 'Kriteria',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='LembagaAkreditasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('kontak', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lembaga Akreditasi',
                'verbose_name_plural': 'Lembaga Akreditasi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('unit_kerja', models.CharField(max_length=255)),
                ('nomor_registrasi', models.CharField(blank=True, max_length=50, null=True)),
                ('is_auditor_ketua', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditor',
                'verbose_name_plural': 'Auditor',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.FloatField(blank=True, null=True)),
                ('deskripsi_kondisi', models.TextField(blank=True, null=True)),
                ('kategori_kondisi', models.CharField(blank=True, choices=[('SESUAI', 'Sesuai'), ('KT_MINOR', 'Ketidaksesuaian Minor'), ('KT_MAYOR', 'Ketidaksesuaian Mayor')], max_length=20, null=True)),
                ('komentar', models.TextField(blank=True, null=True)),
                ('tanggal_audit', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.auditor')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audit',
                'ordering': ['penilaian_diri__indikator__kode'],
            },
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('G', 'Ganjil'), ('P', 'Genap')], max_length=2)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='DRAFT', max_length=20)),
                ('auditor_anggota', models.ManyToManyField(blank=True, related_name='anggota_audit_sessions', to='ami.auditor')),
                ('auditor_ketua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_audit_sessions', to='ami.auditor')),
            ],
            options={
                'verbose_name': 'Sesi Audit',
                'verbose_name_plural': 'Sesi Audit',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='CatatanAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField()),
                ('tanggal_catatan', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='ami.audit')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.auditor')),
                ('dibalas_ke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balasan', to='ami.catatanaudit')),
            ],
            options={
                'verbose_name': 'Catatan Audit',
                'verbose_name_plural': 'Catatan Audit',
                'ordering': ['tanggal_catatan'],
            },
        ),
        migrations.CreateModel(
            name='IndikatorPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('deskripsi', models.TextField()),
                ('panduan', models.TextField(blank=True, null=True)),
                ('skor_maksimal', models.FloatField(default=4.0)),
                ('memiliki_perhitungan_khusus', models.BooleanField(default=False)),
                ('rumus_perhitungan', models.TextField(blank=True, null=True)),
                ('elemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indikator', to='ami.elemen')),
            ],
            options={
                'verbose_name': 'Indikator Penilaian',
                'verbose_name_plural': 'Indikator Penilaian',
                'ordering': ['kode'],
                'unique_together': {('elemen', 'kode')},
            },
        ),
        migrations.AddField(
            model_name='elemen',
            name='kriteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemen', to='ami.kriteria'),
        ),
        migrations.AddField(
            model_name='kriteria',
            name='lembaga_akreditasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria', to='ami.lembagaakreditasi'),
        ),
        migrations.CreateModel(
            name='PenilaianDiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.FloatField(blank=True, null=True)),
                ('bukti_dokumen', models.FileField(blank=True, null=True, upload_to='dokumen_pendukung/')),
                ('komentar', models.TextField(blank=True, null=True)),
                ('tanggal_penilaian', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('BELUM', 'Belum Dinilai'), ('TERISI', 'Sudah Terisi'), ('DIAJUKAN', 'Diajukan untuk Audit')], default='BELUM', max_length=20)),
                ('audit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_diri', to='ami.auditsession')),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami.indikatorpenilaian')),
            ],
            options={
                'verbose_name': 'Penilaian Diri',
                'verbose_name_plural': 'Penilaian Diri',
                'ordering': ['indikator__kode'],
                'unique_together': {('audit_session', 'indikator')},
            },
        ),
        migrations.CreateModel(
            name='DokumenPendukung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dokumen_pendukung/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('penilaian_diri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_pendukung', to='ami.penilaiandiri')),
            ],
            options={
                'verbose_name': 'Dokumen Pendukung',
                'verbose_name_plural': 'Dokumen Pendukung',
                'ordering': ['-tanggal_upload'],
            },
        ),
        migrations.AddField(
            model_name='audit',
            name='penilaian_diri',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='ami.penilaiandiri'),
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('fakultas', models.CharField(max_length=255)),
                ('jenjang', models.CharField(choices=[('D3', 'Diploma 3'), ('D4', 'Diploma 4'), ('S1', 'Sarjana'), ('S2', 'Magister'), ('S3', 'Doktor')], max_length=50)),
                ('akreditasi', models.CharField(blank=True, max_length=2, null=True)),
                ('tanggal_akreditasi', models.DateField(blank=True, null=True)),
                ('lembaga_akreditasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_studi', to='ami.lembagaakreditasi')),
            ],
            options={
                'verbose_name': 'Program Studi',
                'verbose_name_plural': 'Program Studi',
                'ordering': ['kode'],
            },
        ),
        migrations.AddField(
            model_name='auditsession',
            name='program_studi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_sessions', to='ami.programstudi'),
        ),
        migrations.CreateModel(
            name='RekomendasiTindakLanjut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('prioritas', models.CharField(choices=[('TINGGI', 'Tinggi'), ('SEDANG', 'Sedang'), ('RENDAH', 'Rendah')], default='SEDANG', max_length=10)),
                ('tenggat_waktu', models.DateField()),
                ('status', models.CharField(choices=[('BELUM', 'Belum Ditindaklanjuti'), ('SEDANG', 'Sedang Ditindaklanjuti'), ('SELESAI', 'Selesai')], default='BELUM', max_length=20)),
                ('bukti_tindak_lanjut', models.FileField(blank=True, null=True, upload_to='tindak_lanjut/')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekomendasi', to='ami.audit')),
            ],
            options={
                'verbose_name': 'Rekomendasi Tindak Lanjut',
                'verbose_name_plural': 'Rekomendasi Tindak Lanjut',
                'ordering': ['-tenggat_waktu'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='elemen',
            unique_together={('kriteria', 'kode')},
        ),
        migrations.AlterUniqueTogether(
            name='kriteria',
            unique_together={('lembaga_akreditasi', 'kode')},
        ),
        migrations.AlterUniqueTogether(
            name='auditsession',
            unique_together={('program_studi', 'tahun_akademik', 'semester')},
        ),
        migrations.CreateModel(
            name='SkorIndikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.FloatField()),
                ('deskripsi', models.TextField()),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skor_indikator', to='ami.indikatorpenilaian')),
            ],
            options={
                'verbose_name': 'Deskripsi Skor',
                'verbose_name_plural': 'Deskripsi Skor',
                'ordering': ['-skor'],
                'unique_together': {('indikator', 'skor')},
            },
        ),
    ]
