# Generated by Django 5.2 on 2025-09-08 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=30)),
                ("nama", models.CharField(max_length=255)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("aktif", "aktif"), ("tidak aktif", "tidak aktif")],
                        default="aktif",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kriteria",
                "verbose_name_plural": "Kriteria",
                "ordering": ["kode"],
            },
        ),
        migrations.CreateModel(
            name="LembagaAkreditasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=20, unique=True)),
                ("nama", models.CharField(max_length=255, unique=True)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("kontak", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Lembaga Akreditasi",
                "verbose_name_plural": "Lembaga Akreditasi",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Auditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nip", models.CharField(max_length=20, unique=True)),
                ("nama_lengkap", models.CharField(max_length=255)),
                ("jabatan", models.CharField(max_length=255)),
                ("unit_kerja", models.CharField(max_length=255)),
                (
                    "nomor_registrasi",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_auditor_ketua", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditor",
                "verbose_name_plural": "Auditor",
                "ordering": ["nama_lengkap"],
            },
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skor", models.FloatField(blank=True, null=True)),
                ("deskripsi_kondisi", models.TextField(blank=True, null=True)),
                (
                    "kategori_kondisi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SESUAI", "Sesuai"),
                            ("KT_MINOR", "Ketidaksesuaian Minor"),
                            ("KT_MAYOR", "Ketidaksesuaian Mayor"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("komentar", models.TextField(blank=True, null=True)),
                ("tanggal_audit", models.DateTimeField(auto_now_add=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ami.auditor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit",
                "verbose_name_plural": "Audit",
                "ordering": ["penilaian_diri__elemen__kode"],
            },
        ),
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tahun_akademik", models.CharField(max_length=9)),
                (
                    "semester",
                    models.CharField(
                        choices=[("G", "Ganjil"), ("P", "Genap")], max_length=2
                    ),
                ),
                (
                    "tanggal_mulai_penilaian_mandiri",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "tanggal_selesai_penilaian_mandiri",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "tanggal_selesai_penilian_auditor",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENIALAIN MANDIRI", "Penilaian Mandiri"),
                            ("PENIALAIN AUDITOR", "Penilaian Auditor"),
                            ("SELESAI", "SELESAI"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "auditor_anggota",
                    models.ManyToManyField(
                        blank=True,
                        related_name="anggota_audit_sessions",
                        to="ami.auditor",
                    ),
                ),
                (
                    "auditor_ketua",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ketua_audit_sessions",
                        to="ami.auditor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesi Audit",
                "verbose_name_plural": "Sesi Audit",
                "ordering": ["-tanggal_mulai_penilaian_mandiri"],
            },
        ),
        migrations.CreateModel(
            name="CatatanAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catatan", models.TextField()),
                ("tanggal_catatan", models.DateTimeField(auto_now_add=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catatan",
                        to="ami.audit",
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ami.auditor",
                    ),
                ),
                (
                    "dibalas_ke",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="balasan",
                        to="ami.catatanaudit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catatan Audit",
                "verbose_name_plural": "Catatan Audit",
                "ordering": ["tanggal_catatan"],
            },
        ),
        migrations.CreateModel(
            name="Elemen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=30)),
                ("nama", models.CharField(max_length=255)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("panduan", models.TextField(blank=True, null=True)),
                ("skor_maksimal", models.FloatField(default=4.0)),
                (
                    "status",
                    models.CharField(
                        choices=[("aktif", "aktif"), ("tidak aktif", "tidak aktif")],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                (
                    "kriteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elemen",
                        to="ami.kriteria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elemen",
                "verbose_name_plural": "Elemen",
                "ordering": ["kode"],
                "unique_together": {("kriteria", "kode")},
            },
        ),
        migrations.AddField(
            model_name="kriteria",
            name="lembaga_akreditasi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kriteria",
                to="ami.lembagaakreditasi",
            ),
        ),
        migrations.CreateModel(
            name="PenilaianDiri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skor", models.FloatField(blank=True, null=True)),
                ("bukti_dokumen", models.URLField(blank=True, null=True)),
                ("komentar", models.TextField(blank=True, null=True)),
                ("tanggal_penilaian", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BELUM", "Belum Dinilai"),
                            ("TERISI", "Sudah Terisi"),
                            ("DIAJUKAN", "Diajukan untuk Audit"),
                        ],
                        default="BELUM",
                        max_length=20,
                    ),
                ),
                (
                    "audit_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penilaian_diri",
                        to="ami.auditsession",
                    ),
                ),
                (
                    "elemen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ami.elemen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penilaian Diri",
                "verbose_name_plural": "Penilaian Diri",
                "ordering": ["elemen__kode"],
                "unique_together": {("audit_session", "elemen")},
            },
        ),
        migrations.CreateModel(
            name="DokumenPendukung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="dokumen_pendukung/")),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("tanggal_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "penilaian_diri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumen_pendukung",
                        to="ami.penilaiandiri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumen Pendukung",
                "verbose_name_plural": "Dokumen Pendukung",
                "ordering": ["-tanggal_upload"],
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="penilaian_diri",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit",
                to="ami.penilaiandiri",
            ),
        ),
        migrations.CreateModel(
            name="ProgramStudi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=10, unique=True)),
                ("nama", models.CharField(max_length=255)),
                (
                    "fakultas",
                    models.CharField(
                        choices=[
                            ("FKIP", "FKIP"),
                            ("FISIP", "FISIP"),
                            ("FEB", "FEB"),
                            ("FAKUM", "FAKUM"),
                            ("FAPERTA", "FAPERTA"),
                            ("FATEK", "FATEK"),
                            ("FMIPA", "FMIPA"),
                            ("FAHUT", "FAHUT"),
                            ("FK", "FK"),
                            ("FAPETKAN", "FAPETKAN"),
                            ("FKM", "FKM"),
                            ("Pascasarjana", "Pascasarjana"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "jenjang",
                    models.CharField(
                        choices=[
                            ("D3", "Diploma 3"),
                            ("D4", "Diploma 4"),
                            ("S1", "Sarjana"),
                            ("S2", "Magister"),
                            ("S3", "Doktor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "akreditasi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unggul", "UNGGUL"),
                            ("baik_sekali", "BAIK SEKALI"),
                            ("baik", "BAIK"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("belum", "Belum Terakreditasi"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("tanggal_akreditasi", models.DateField(blank=True, null=True)),
                (
                    "koordinator",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="koordinator_prodi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lembaga_akreditasi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_studi",
                        to="ami.lembagaakreditasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Studi",
                "verbose_name_plural": "Program Studi",
                "ordering": ["kode"],
            },
        ),
        migrations.AddField(
            model_name="auditsession",
            name="program_studi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_sessions",
                to="ami.programstudi",
            ),
        ),
        migrations.CreateModel(
            name="RekomendasiTindakLanjut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deskripsi", models.TextField()),
                (
                    "prioritas",
                    models.CharField(
                        choices=[
                            ("TINGGI", "Tinggi"),
                            ("SEDANG", "Sedang"),
                            ("RENDAH", "Rendah"),
                        ],
                        default="SEDANG",
                        max_length=10,
                    ),
                ),
                ("tenggat_waktu", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BELUM", "Belum Ditindaklanjuti"),
                            ("SEDANG", "Sedang Ditindaklanjuti"),
                            ("SELESAI", "Selesai"),
                        ],
                        default="BELUM",
                        max_length=20,
                    ),
                ),
                (
                    "bukti_tindak_lanjut",
                    models.FileField(blank=True, null=True, upload_to="tindak_lanjut/"),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rekomendasi",
                        to="ami.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rekomendasi Tindak Lanjut",
                "verbose_name_plural": "Rekomendasi Tindak Lanjut",
                "ordering": ["-tenggat_waktu"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="kriteria", unique_together={("lembaga_akreditasi", "kode")},
        ),
        migrations.AlterUniqueTogether(
            name="auditsession",
            unique_together={("program_studi", "tahun_akademik", "semester")},
        ),
    ]
