# Generated by Django 5.2 on 2025-09-08 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ami", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(model_name="auditor", old_name="nip", new_name="nuptk",),
        migrations.RemoveField(model_name="programstudi", name="koordinator",),
        migrations.CreateModel(
            name="KoordinatorProgramStudi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nuptk", models.CharField(max_length=20, unique=True)),
                ("nama_lengkap", models.CharField(max_length=255)),
                (
                    "program_studi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="koordinators",
                        to="ami.programstudi",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Koordinator Program Studi",
                "verbose_name_plural": "Koordinator Program Studi",
                "ordering": ["nama_lengkap"],
            },
        ),
    ]
