# Generated by Django 5.2 on 2025-09-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstudi',
            name='fakultas',
            field=models.CharField(choices=[('FKIP', 'FKIP'), ('FISIP', 'FISIP'), ('FEB', 'FEB'), ('FAKUM', 'FAKUM'), ('FAPERTA', 'FAPERTA'), ('FATEK', 'FATEK'), ('FMIPA', 'FMIPA'), ('FAHUT', 'FAHUT'), ('FK', 'FK'), ('FAPETKAN', 'FAPETKAN'), ('FKM', 'FKM'), ('Pascasarjana', 'Pascasarjana')], max_length=200),
        ),
    ]
