# Generated by Django 5.2 on 2025-09-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ami", "0002_rename_nip_auditor_nuptk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kriteria",
            name="kode",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
