# Generated by Django 5.2 on 2025-09-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0002_alter_programstudi_fakultas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstudi',
            name='akreditasi',
            field=models.CharField(blank=True, choices=[('unggul', 'UNGGUL'), ('baik_sekali', 'BAIK SEKALI'), ('baik', 'BAIK'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('belum', 'Belum Terakreditasi')], max_length=50, null=True),
        ),
    ]
