# Generated by Django 5.2 on 2025-09-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0003_alter_programstudi_akreditasi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditsession',
            options={'ordering': ['-tanggal_mulai_penilaian_mandiri'], 'verbose_name': 'Sesi Audit', 'verbose_name_plural': 'Sesi Audit'},
        ),
        migrations.RenameField(
            model_name='auditsession',
            old_name='tanggal_selesai',
            new_name='tanggal_mulai_penilaian_mandiri',
        ),
        migrations.RemoveField(
            model_name='auditsession',
            name='tanggal_mulai_penilaian_mandiri',
        ),
        migrations.AddField(
            model_name='auditsession',
            name='tanggal_selesai_penilaian_mandiri',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='tanggal_selesai_penilian_auditor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENIALAIN_MANDIRI', 'Penilaian Mandiri'), ('PENIALAIN_AUDITOR', 'Penilaian Auditor'), ('SELESAI', 'SELESAI')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='elemen',
            name='kode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='indikatorpenilaian',
            name='kode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='kode',
            field=models.CharField(max_length=30),
        ),
    ]
