# Generated by Django 5.2 on 2025-09-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0003_alter_kriteria_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='status',
            field=models.CharField(choices=[('aktif', 'aktif'), ('tidak aktif', 'tidak aktif')], default='aktif', max_length=20),
        ),
    ]
