# Generated by Django 5.2 on 2025-09-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ami", "0004_auditor_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditsession",
            old_name="tanggal_selesai_penilian_auditor",
            new_name="tanggal_selesai_penilaian_auditor",
        ),
    ]
