# Generated by Django 5.2 on 2025-09-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0005_rename_tanggal_selesai_penilian_auditor_auditsession_tanggal_selesai_penilaian_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='tanggal_mulai_penilaian_auditor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENILAIAN_MANDIRI', 'Penilaian Mandiri'), ('PENILAIAN_AUDITOR', 'Penilaian Auditor'), ('SELESAI', 'SELESAI')], default='DRAFT', max_length=20),
        ),
    ]
