# Generated by Django 5.2 on 2025-09-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ami", "0006_auditsession_tanggal_mulai_penilaian_auditor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditsession", name="tanggal_mulai_penilaian_auditor",
        ),
    ]
