# Generated by Django 5.2 on 2025-09-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ami", "0007_remove_auditsession_tanggal_mulai_penilaian_auditor"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditsession",
            name="tanggal_mulai_penilaian_auditor",
            field=models.DateField(blank=True, null=True),
        ),
    ]
