# Generated by Django 5.2 on 2025-09-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ami", "0008_auditsession_tanggal_mulai_penilaian_auditor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="deskripsi_kondisi",
            field=models.TextField(default="Tolong Tuliskan Deskrpisi Penilaian"),
        ),
    ]
