# Generated by Django 5.2 on 2025-09-04 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LembagaAkreditasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('kode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=50, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('sertifikat_status', models.CharField(choices=[('ada', 'Ada'), ('tidak_ada', 'Tidak Ada')], default='tidak_ada', max_length=20)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif')], default='aktif', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('lembaga_akreditasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodi', to='sipmi_core.lembagaakreditasi')),
            ],
        ),
        migrations.CreateModel(
            name='PenugasanAuditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('ditunda', 'Ditunda')], default='aktif', max_length=20)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipmi_core.auditor')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipmi_core.programstudi')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('belum_mulai', 'Belum Mulai'), ('berlangsung', 'Berlangsung'), ('selesai', 'Selesai')], max_length=20)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipmi_core.programstudi')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalAMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('terjadwal', 'Terjadwal'), ('berlangsung', 'Berlangsung'), ('selesai', 'Selesai')], default='terjadwal', max_length=20)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipmi_core.auditor')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipmi_core.programstudi')),
            ],
        ),
        migrations.CreateModel(
            name='Standar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('lembaga_akreditasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standar', to='sipmi_core.lembagaakreditasi')),
            ],
        ),
        migrations.CreateModel(
            name='KriteriaED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif')], default='aktif', max_length=20)),
                ('lembaga_akreditasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria', to='sipmi_core.lembagaakreditasi')),
                ('standar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria', to='sipmi_core.standar')),
            ],
        ),
    ]
