# Generated by Django 5.2 on 2025-09-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipmi_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstudi',
            name='koprodi',
            field=models.CharField(default='', max_length=100),
        ),
    ]
